### ISSUE TITLE
嘛，关于实现的一点小疑问

### ISSUE THREAD

**Issue by Tarhyru** [bimOvO/Kratos-Rebirth#1]
...我之前见过和这个一样的非HEXO主题...看起来好像是单页面应用...当时很感兴趣..
但，我用的HEXO嘛，就没有去研究那个..
这个我看了下似乎也是单页面应用这种模式的，点击以后不是跳转而是一个XHR请求....
看起来是后端路由？在HEXO的框架下..这个是通过什么手段实现的呢？
总不至于是前端发起GET请求然后处理获得的HTML页面吧...
如果是这样....恩..拦截普通的URL跳转...发起GET请求，页面整体替换/部分替换..毛病倒是没有....

**Comment by bimOvO** [comment]
其实是jQuery封装的ajax技术\~单击链接时候JavaScript先阻塞跳转请求，然后后台处理读入的文件数据，再替换掉页面部分\~配合pushState更新浏览器地址栏和历史纪录\~结合起来就简称pjax啦o(*￣▽￣*)ブ
可以参见[W3School-ajax](http://www.w3school.com.cn/jquery/ajax_ajax.asp)和[jQuery官网的文档](https://api.jquery.com/category/ajax/)哦w
然后咱的pjax代码是从[INLOJV封装的自用WordPress全站PJAX代码](http://www.inlojv.com/4679.html)这里移植过来的说φ(゜▽゜*)♪

**Comment by Tarhyru** [comment]
_(:з」∠)_的确这样做，改造成本是最低的....细想下来很合理，我也改造一个试试去..
