### ISSUE TITLE
Stackpath CDN Problem

### ISSUE THREAD

**Issue by hifocus** [bimOvO/Kratos-Rebirth#2]
![image](https://user-images.githubusercontent.com/30528433/42645384-6eca28da-8630-11e8-8eb3-fc7e2d8a33ce.png)

You use a Stackpath CDN to load the `font-awesome.min.css` and some other files. If users access your site in Mainland China, they will have a bad experience while loading the css files.

You might want to use `Google Page Insight` in order to spot out the exist problems.

**Comment by hifocus** [comment]
And you could merge the `js` and `css` files to reduce the request amount.

**Comment by bimOvO** [comment]
Good idea~Thanks for the suggestions!
